---
language: php
os:
- linux
php:
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- composer install
- phpenv rehash

matrix:
  allow_failures:
  - php: 5.6
  
script:
- bin/phpcs
- bin/phpdoc -f phpdoc.dist.xml